version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install s3pypi
      - pip install dephell
  pre_build:
    commands:
      - echo "Pre build"
      - cd src/main/python/voyclib
  build:
    commands:
      - echo "Pushing to s3"
      - dephell deps convert --from=pyproject.toml --to=setup.py
      - s3pypi --bucket $BUCKET --secret $SECRET
  post_build:
    commands:
      - echo "Build done - `date`"